"""empty message

Revision ID: 1674a58d7d0c
Revises: 1bfaf16fe5f1
Create Date: 2016-07-30 12:42:47.440357

"""

# revision identifiers, used by Alembic.
revision = '1674a58d7d0c'
down_revision = '1bfaf16fe5f1'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('auto_discover', sa.Boolean(), nullable=True))
    op.add_column('devices', sa.Column('uuid', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'uuid')
    op.drop_column('assets', 'auto_discover')
    ### end Alembic commands ###
