"""empty message

Revision ID: 1bfaf16fe5f1
Revises: 9c0f41d6933a
Create Date: 2016-07-30 11:46:02.984280

"""

# revision identifiers, used by Alembic.
revision = '1bfaf16fe5f1'
down_revision = '9c0f41d6933a'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('auto_discover', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'auto_discover')
    ### end Alembic commands ###
