"""empty message

Revision ID: 1e0e09721693
Revises: None
Create Date: 2016-06-27 11:08:59.540893

"""

# revision identifiers, used by Alembic.
revision = '1e0e09721693'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idcs', sa.Column('contactname', sa.String(length=64), nullable=True))
    op.add_column('idcs', sa.Column('contactphone', sa.String(length=64), nullable=True))
    op.drop_column('idcs', 'contactid')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('idcs', sa.Column('contactid', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('idcs', 'contactphone')
    op.drop_column('idcs', 'contactname')
    ### end Alembic commands ###
