"""empty message

Revision ID: 1fcd25f456ee
Revises: a8968c310f7b
Create Date: 2016-05-28 17:30:15.338780

"""

# revision identifiers, used by Alembic.
revision = '1fcd25f456ee'
down_revision = 'a8968c310f7b'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('cpucount', sa.Integer(), nullable=True))
    op.add_column('device', sa.Column('cpumodel', sa.String(length=64), nullable=True))
    op.add_column('device', sa.Column('disksize', sa.Integer(), nullable=True))
    op.add_column('device', sa.Column('idc', sa.String(length=64), nullable=True))
    op.add_column('device', sa.Column('inputtime', sa.DateTime(), nullable=True))
    op.add_column('device', sa.Column('instaff', sa.String(length=64), nullable=True))
    op.add_column('device', sa.Column('is_virtualization', sa.Boolean(), nullable=True))
    op.add_column('device', sa.Column('isdelete', sa.Boolean(), nullable=True))
    op.add_column('device', sa.Column('memcount', sa.Integer(), nullable=True))
    op.add_column('device', sa.Column('networkportcount', sa.Integer(), nullable=True))
    op.add_column('device', sa.Column('os', sa.String(length=64), nullable=True))
    op.add_column('device', sa.Column('other_ip', sa.String(length=15), nullable=True))
    op.add_column('device', sa.Column('privide_ip', sa.String(length=15), nullable=True))
    op.add_column('device', sa.Column('public_ip', sa.String(length=15), nullable=True))
    op.add_column('device', sa.Column('rack', sa.String(length=64), nullable=True))
    op.add_column('device', sa.Column('raidmodel', sa.String(length=64), nullable=True))
    op.add_column('device', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('device', sa.Column('remotecardip', sa.String(length=64), nullable=True))
    op.add_column('device', sa.Column('singlemem', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'singlemem')
    op.drop_column('device', 'remotecardip')
    op.drop_column('device', 'remarks')
    op.drop_column('device', 'raidmodel')
    op.drop_column('device', 'rack')
    op.drop_column('device', 'public_ip')
    op.drop_column('device', 'privide_ip')
    op.drop_column('device', 'other_ip')
    op.drop_column('device', 'os')
    op.drop_column('device', 'networkportcount')
    op.drop_column('device', 'memcount')
    op.drop_column('device', 'isdelete')
    op.drop_column('device', 'is_virtualization')
    op.drop_column('device', 'instaff')
    op.drop_column('device', 'inputtime')
    op.drop_column('device', 'idc')
    op.drop_column('device', 'disksize')
    op.drop_column('device', 'cpumodel')
    op.drop_column('device', 'cpucount')
    ### end Alembic commands ###
