"""empty message

Revision ID: 20688447519d
Revises: 8c600384959c
Create Date: 2016-06-05 22:21:40.864158

"""

# revision identifiers, used by Alembic.
revision = '20688447519d'
down_revision = '8c600384959c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('powerstatus', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'powerstatus')
    ### end Alembic commands ###
