"""empty message

Revision ID: 26e963bc678d
Revises: ce4eaa48dabb
Create Date: 2016-07-29 11:57:05.921589

"""

# revision identifiers, used by Alembic.
revision = '26e963bc678d'
down_revision = 'ce4eaa48dabb'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipResourcePools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idc_id', sa.Integer(), nullable=True),
    sa.Column('netmask', sa.String(length=32), nullable=True),
    sa.Column('gateway', sa.String(length=32), nullable=True),
    sa.Column('range', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Boolean(), nullable=True),
    sa.Column('vlan', sa.String(length=10), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['idc_id'], ['idcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ipResourceManage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipPool_id', sa.Integer(), nullable=True),
    sa.Column('ip', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('devicePort_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['devicePort_id'], ['devicePorts.id'], ),
    sa.ForeignKeyConstraint(['ipPool_id'], ['ipResourcePools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ipManage')
    op.drop_table('ipPools')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipPools',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('idc_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('netmask', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('gateway', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('range', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('type', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('vlan', mysql.VARCHAR(length=10), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['idc_id'], [u'idcs.id'], name=u'ippools_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('ipManage',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('ipPool_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('ipaddress', mysql.VARCHAR(length=20), nullable=True),
    sa.Column('status', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('devicePort_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['devicePort_id'], [u'devicePorts.id'], name=u'ipmanage_ibfk_1'),
    sa.ForeignKeyConstraint(['ipPool_id'], [u'ipPools.id'], name=u'ipmanage_ibfk_2'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('ipResourceManage')
    op.drop_table('ipResourcePools')
    ### end Alembic commands ###
