"""empty message

Revision ID: 327d21f1ae6d
Revises: None
Create Date: 2016-06-30 12:21:25.423695

"""

# revision identifiers, used by Alembic.
revision = '327d21f1ae6d'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devicePorts', sa.Column('name', sa.String(length=64), nullable=True))
    op.drop_column('devices', 'singlemem')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('singlemem', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('devicePorts', 'name')
    ### end Alembic commands ###
