"""empty message

Revision ID: 32d8e7250ca6
Revises: 49634ce8d9d6
Create Date: 2016-08-05 16:04:47.090721

"""

# revision identifiers, used by Alembic.
revision = '32d8e7250ca6'
down_revision = '49634ce8d9d6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtMachine', sa.Column('uuid', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtMachine', 'uuid')
    ### end Alembic commands ###
