"""empty message

Revision ID: 49634ce8d9d6
Revises: 8f1b4f6a4443
Create Date: 2016-08-02 17:57:15.929654

"""

# revision identifiers, used by Alembic.
revision = '49634ce8d9d6'
down_revision = '8f1b4f6a4443'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deviceNetwork', sa.Column('hostname', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deviceNetwork', 'hostname')
    ### end Alembic commands ###
