"""empty message

Revision ID: 5170d598d7df
Revises: None
Create Date: 2016-07-03 17:27:50.847802

"""

# revision identifiers, used by Alembic.
revision = '5170d598d7df'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('asset_id', sa.Integer(), nullable=True))
    op.drop_index('ix_devices_an', table_name='devices')
    op.drop_index('ix_devices_sn', table_name='devices')
    op.drop_constraint(u'devices_ibfk_1', 'devices', type_='foreignkey')
    op.create_foreign_key(None, 'devices', 'assets', ['asset_id'], ['id'])
    op.drop_column('devices', 'onstatus')
    op.drop_column('devices', 'managedept')
    op.drop_column('devices', 'koriyasustarttime')
    op.drop_column('devices', 'usestarttime')
    op.drop_column('devices', 'equipprice')
    op.drop_column('devices', 'useendtime')
    op.drop_column('devices', 'managestaff')
    op.drop_column('devices', 'mainuses')
    op.drop_column('devices', 'usestaff')
    op.drop_column('devices', 'an')
    op.drop_column('devices', 'usedept')
    op.drop_column('devices', 'sn')
    op.drop_column('devices', 'dateofmanufacture')
    op.drop_column('devices', 'model')
    op.drop_column('devices', 'deviceType_id')
    op.drop_column('devices', 'brand')
    op.drop_column('devices', 'koriyasuendtime')
    op.drop_column('devices', 'manufacturer')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('manufacturer', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('devices', sa.Column('koriyasuendtime', mysql.DATETIME(), nullable=True))
    op.add_column('devices', sa.Column('brand', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('devices', sa.Column('deviceType_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('model', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('devices', sa.Column('dateofmanufacture', mysql.DATETIME(), nullable=True))
    op.add_column('devices', sa.Column('sn', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('devices', sa.Column('usedept', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('devices', sa.Column('an', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('devices', sa.Column('usestaff', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('devices', sa.Column('mainuses', mysql.VARCHAR(length=128), nullable=True))
    op.add_column('devices', sa.Column('managestaff', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('devices', sa.Column('useendtime', mysql.DATETIME(), nullable=True))
    op.add_column('devices', sa.Column('equipprice', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.add_column('devices', sa.Column('usestarttime', mysql.DATETIME(), nullable=True))
    op.add_column('devices', sa.Column('koriyasustarttime', mysql.DATETIME(), nullable=True))
    op.add_column('devices', sa.Column('managedept', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('devices', sa.Column('onstatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.create_foreign_key(u'devices_ibfk_1', 'devices', 'devicetype', ['deviceType_id'], ['id'])
    op.create_index('ix_devices_sn', 'devices', ['sn'], unique=True)
    op.create_index('ix_devices_an', 'devices', ['an'], unique=True)
    op.drop_column('devices', 'asset_id')
    ### end Alembic commands ###
