"""empty message

Revision ID: 53e3e351314e
Revises: c33c061f54dc
Create Date: 2016-05-28 21:23:31.410497

"""

# revision identifiers, used by Alembic.
revision = '53e3e351314e'
down_revision = 'c33c061f54dc'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('idcname', sa.Integer(), nullable=True))
    op.add_column('devices', sa.Column('private_ip', sa.String(length=15), nullable=True))
    op.create_foreign_key(None, 'devices', 'racks', ['rack'], ['id'])
    op.create_foreign_key(None, 'devices', 'idcs', ['idcname'], ['id'])
    op.drop_column('devices', 'privide_ip')
    op.add_column('racks', sa.Column('idcname', sa.Integer(), nullable=True))
    op.add_column('racks', sa.Column('name', sa.String(length=64), nullable=True))
    op.create_foreign_key(None, 'racks', 'idcs', ['idcname'], ['id'])
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'racks', type_='foreignkey')
    op.drop_column('racks', 'name')
    op.drop_column('racks', 'idcname')
    op.add_column('devices', sa.Column('privide_ip', mysql.VARCHAR(length=15), nullable=True))
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_constraint(None, 'devices', type_='foreignkey')
    op.drop_column('devices', 'private_ip')
    op.drop_column('devices', 'idcname')
    ### end Alembic commands ###
