"""empty message

Revision ID: 541a49fd0aad
Revises: 327d21f1ae6d
Create Date: 2016-06-30 12:55:07.728833

"""

# revision identifiers, used by Alembic.
revision = '541a49fd0aad'
down_revision = '327d21f1ae6d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'networkportcount')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('networkportcount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
