"""empty message

Revision ID: 5c747ca40b41
Revises: 7e0e879bb71a
Create Date: 2016-10-23 20:12:10.840239

"""

# revision identifiers, used by Alembic.
revision = '5c747ca40b41'
down_revision = '7e0e879bb71a'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SparePart',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('SparePartManagement')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('SparePartManagement',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('SparePart')
    ### end Alembic commands ###
