"""empty message

Revision ID: 69b977399772
Revises: None
Create Date: 2016-07-29 10:21:46.028288

"""

# revision identifiers, used by Alembic.
revision = '69b977399772'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipPools',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('idc_id', sa.Integer(), nullable=True),
    sa.Column('netmask', sa.String(length=32), nullable=True),
    sa.Column('gateway', sa.String(length=32), nullable=True),
    sa.Column('range', sa.String(length=64), nullable=True),
    sa.Column('type', sa.Boolean(), nullable=True),
    sa.Column('vlan', sa.String(length=10), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['idc_id'], ['idcs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipPools')
    ### end Alembic commands ###
