"""empty message

Revision ID: 790411817c10
Revises: ba220efeb37e
Create Date: 2016-07-31 13:30:29.891999

"""

# revision identifiers, used by Alembic.
revision = '790411817c10'
down_revision = 'ba220efeb37e'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('useracksize', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'useracksize')
    ### end Alembic commands ###
