"""empty message

Revision ID: 7e0e879bb71a
Revises: None
Create Date: 2016-10-23 19:48:38.233039

"""

# revision identifiers, used by Alembic.
revision = '7e0e879bb71a'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ServiceProvider',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serviceProvider', sa.String(length=64), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('ServiceProviderContact',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serviceProvider_id', sa.Integer(), nullable=True),
    sa.Column('service', sa.Integer(), nullable=True),
    sa.Column('contact', sa.String(length=32), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['serviceProvider_id'], ['ServiceProvider.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('ServiceProviderContactManagement')
    op.drop_table('ServiceProviderManagement')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ServiceProviderManagement',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('serviceProvider', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('instaff', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('inputtime', mysql.DATETIME(), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('ServiceProviderContactManagement',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('serviceProvider_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('service', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('contact', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('instaff', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('inputtime', mysql.DATETIME(), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['serviceProvider_id'], [u'ServiceProviderManagement.id'], name=u'serviceprovidercontactmanagement_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('ServiceProviderContact')
    op.drop_table('ServiceProvider')
    ### end Alembic commands ###
