"""empty message

Revision ID: 7eb921f47794
Revises: 1fcd25f456ee
Create Date: 2016-05-28 17:32:50.238620

"""

# revision identifiers, used by Alembic.
revision = '7eb921f47794'
down_revision = '1fcd25f456ee'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('hostname', sa.String(length=64), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('device', 'hostname')
    ### end Alembic commands ###
