"""empty message

Revision ID: 87b39b213b12
Revises: None
Create Date: 2016-05-27 19:24:43.485482

"""

# revision identifiers, used by Alembic.
revision = '87b39b213b12'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('phone', sa.Integer(), nullable=True))
    op.add_column('users', sa.Column('qq', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'qq')
    op.drop_column('users', 'phone')
    ### end Alembic commands ###
