"""empty message

Revision ID: 9e73ebde95f8
Revises: f0fa8c0e67be
Create Date: 2016-05-28 18:27:06.241744

"""

# revision identifiers, used by Alembic.
revision = '9e73ebde95f8'
down_revision = 'f0fa8c0e67be'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('idcs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ispid', sa.String(length=64), nullable=True),
    sa.Column('contactid', sa.String(length=64), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('nettype', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('adnature', sa.String(length=64), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('racks',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff', sa.String(length=64), nullable=True),
    sa.Column('seatno', sa.String(length=64), nullable=True),
    sa.Column('furnituretype', sa.String(length=64), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('remainsize', sa.String(length=64), nullable=True),
    sa.Column('electrictype', sa.String(length=32), nullable=True),
    sa.Column('electricno', sa.String(length=32), nullable=True),
    sa.Column('electriccapacity', sa.String(length=32), nullable=True),
    sa.Column('leftelectric', sa.String(length=64), nullable=True),
    sa.Column('seattime', sa.DateTime(), nullable=True),
    sa.Column('expiretime', sa.DateTime(), nullable=True),
    sa.Column('nextpaytime', sa.DateTime(), nullable=True),
    sa.Column('money', sa.String(length=64), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('hostname', sa.String(length=64), nullable=True),
    sa.Column('privide_ip', sa.String(length=15), nullable=True),
    sa.Column('public_ip', sa.String(length=15), nullable=True),
    sa.Column('other_ip', sa.String(length=15), nullable=True),
    sa.Column('rack', sa.String(length=64), nullable=True),
    sa.Column('idc', sa.String(length=64), nullable=True),
    sa.Column('is_virtualization', sa.Boolean(), nullable=True),
    sa.Column('asset', sa.Integer(), nullable=True),
    sa.Column('cpumodel', sa.String(length=64), nullable=True),
    sa.Column('cpucount', sa.Integer(), nullable=True),
    sa.Column('memcount', sa.Integer(), nullable=True),
    sa.Column('singlemem', sa.Integer(), nullable=True),
    sa.Column('raidmodel', sa.String(length=64), nullable=True),
    sa.Column('disksize', sa.Integer(), nullable=True),
    sa.Column('remotecardip', sa.String(length=64), nullable=True),
    sa.Column('networkportcount', sa.Integer(), nullable=True),
    sa.Column('os', sa.String(length=64), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['asset'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.drop_table('rack')
    op.drop_table('device')
    op.drop_table('IDC')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IDC',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('ispid', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('contactid', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('nettype', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('address', mysql.VARCHAR(length=128), nullable=True),
    sa.Column('city', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('adnature', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('instaff', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('inputtime', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('device',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('asset', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cpucount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('cpumodel', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('disksize', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('idc', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('inputtime', mysql.DATETIME(), nullable=True),
    sa.Column('instaff', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('is_virtualization', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('memcount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('networkportcount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('os', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('other_ip', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('privide_ip', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('public_ip', mysql.VARCHAR(length=15), nullable=True),
    sa.Column('rack', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('raidmodel', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.Column('remotecardip', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('singlemem', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('hostname', mysql.VARCHAR(length=64), nullable=True),
    sa.ForeignKeyConstraint(['asset'], [u'assets.id'], name=u'device_ibfk_1'),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.create_table('rack',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('staff', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('seatno', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('furnituretype', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('size', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('remainsize', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('electrictype', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('electricno', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('electriccapacity', mysql.VARCHAR(length=32), nullable=True),
    sa.Column('leftelectric', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('seattime', mysql.DATETIME(), nullable=True),
    sa.Column('expiretime', mysql.DATETIME(), nullable=True),
    sa.Column('nextpaytime', mysql.DATETIME(), nullable=True),
    sa.Column('money', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.Column('instaff', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('inputtime', mysql.DATETIME(), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    op.drop_table('devices')
    op.drop_table('racks')
    op.drop_table('idcs')
    ### end Alembic commands ###
