"""empty message

Revision ID: 9fa02b359b34
Revises: None
Create Date: 2016-05-28 15:16:24.338929

"""

# revision identifiers, used by Alembic.
revision = '9fa02b359b34'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('assettype', sa.Integer(), nullable=True))
    op.drop_constraint(u'assets_ibfk_1', 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'assettype', ['assettype'], ['id'])
    op.drop_column('assets', 'asset')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('asset', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key(u'assets_ibfk_1', 'assets', 'assettype', ['asset'], ['id'])
    op.drop_column('assets', 'assettype')
    ### end Alembic commands ###
