"""empty message

Revision ID: a3ddb8ccea83
Revises: ddd227fea0cd
Create Date: 2016-06-19 15:54:44.011811

"""

# revision identifiers, used by Alembic.
revision = 'a3ddb8ccea83'
down_revision = 'ddd227fea0cd'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('powermanage_id', sa.String(length=256), nullable=True))
    op.add_column('devices', sa.Column('powermanage_ip', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('powermanage_password', sa.String(length=64), nullable=True))
    op.add_column('devices', sa.Column('powermanage_user', sa.String(length=64), nullable=True))
    op.drop_column('devices', 'remotecardip')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('remotecardip', mysql.VARCHAR(length=64), nullable=True))
    op.drop_column('devices', 'powermanage_user')
    op.drop_column('devices', 'powermanage_password')
    op.drop_column('devices', 'powermanage_ip')
    op.drop_column('devices', 'powermanage_id')
    ### end Alembic commands ###
