"""empty message

Revision ID: a6e969784438
Revises: f18a59c627a0
Create Date: 2016-07-30 16:39:33.010228

"""

# revision identifiers, used by Alembic.
revision = 'a6e969784438'
down_revision = 'f18a59c627a0'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devicePorts', sa.Column('netmask', sa.String(length=32), nullable=True))
    op.drop_column('devicePorts', 'mask')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devicePorts', sa.Column('mask', mysql.VARCHAR(length=32), nullable=True))
    op.drop_column('devicePorts', 'netmask')
    ### end Alembic commands ###
