"""empty message

Revision ID: a8968c310f7b
Revises: e59dd178a641
Create Date: 2016-05-28 17:12:11.542462

"""

# revision identifiers, used by Alembic.
revision = 'a8968c310f7b'
down_revision = 'e59dd178a641'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('asset', sa.Integer(), nullable=True))
    op.drop_constraint(u'device_ibfk_1', 'device', type_='foreignkey')
    op.create_foreign_key(None, 'device', 'assets', ['asset'], ['id'])
    op.drop_column('device', 'asset_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('device', sa.Column('asset_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'device', type_='foreignkey')
    op.create_foreign_key(u'device_ibfk_1', 'device', 'assets', ['asset_id'], ['id'])
    op.drop_column('device', 'asset')
    ### end Alembic commands ###
