"""empty message

Revision ID: adc22ecbf0da
Revises: 541a49fd0aad
Create Date: 2016-06-30 13:08:53.121585

"""

# revision identifiers, used by Alembic.
revision = 'adc22ecbf0da'
down_revision = '541a49fd0aad'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'flowstatus')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('flowstatus', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    ### end Alembic commands ###
