"""empty message

Revision ID: ba220efeb37e
Revises: a6e969784438
Create Date: 2016-07-30 18:39:25.561764

"""

# revision identifiers, used by Alembic.
revision = 'ba220efeb37e'
down_revision = 'a6e969784438'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devicePowers', sa.Column('device_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'devicePowers', 'devices', ['device_id'], ['id'])
    op.drop_constraint(u'devices_ibfk_4', 'devices', type_='foreignkey')
    op.drop_column('devices', 'powermanage_id')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('powermanage_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.create_foreign_key(u'devices_ibfk_4', 'devices', 'devicePowers', ['powermanage_id'], ['id'])
    op.drop_constraint(None, 'devicePowers', type_='foreignkey')
    op.drop_column('devicePowers', 'device_id')
    ### end Alembic commands ###
