"""empty message

Revision ID: c33c061f54dc
Revises: 9e73ebde95f8
Create Date: 2016-05-28 18:49:35.618309

"""

# revision identifiers, used by Alembic.
revision = 'c33c061f54dc'
down_revision = '9e73ebde95f8'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('devices', sa.Column('memsize', sa.String(length=64), nullable=True))
    op.drop_column('devices', 'memcount')
    op.add_column('idcs', sa.Column('netout', sa.String(length=64), nullable=True))
    op.add_column('racks', sa.Column('racktype', sa.String(length=64), nullable=True))
    op.add_column('racks', sa.Column('renttime', sa.DateTime(), nullable=True))
    op.add_column('racks', sa.Column('site', sa.String(length=64), nullable=True))
    op.add_column('racks', sa.Column('usesize', sa.String(length=64), nullable=True))
    op.drop_column('racks', 'seattime')
    op.drop_column('racks', 'furnituretype')
    op.drop_column('racks', 'seatno')
    op.drop_column('racks', 'size')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('racks', sa.Column('size', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('racks', sa.Column('seatno', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('racks', sa.Column('furnituretype', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('racks', sa.Column('seattime', mysql.DATETIME(), nullable=True))
    op.drop_column('racks', 'usesize')
    op.drop_column('racks', 'site')
    op.drop_column('racks', 'renttime')
    op.drop_column('racks', 'racktype')
    op.drop_column('idcs', 'netout')
    op.add_column('devices', sa.Column('memcount', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_column('devices', 'memsize')
    ### end Alembic commands ###
