"""empty message

Revision ID: ce4eaa48dabb
Revises: 69b977399772
Create Date: 2016-07-29 10:24:42.398759

"""

# revision identifiers, used by Alembic.
revision = 'ce4eaa48dabb'
down_revision = '69b977399772'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ipManage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ipPool_id', sa.Integer(), nullable=True),
    sa.Column('ipaddress', sa.String(length=20), nullable=True),
    sa.Column('status', sa.Integer(), nullable=True),
    sa.Column('devicePort_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['devicePort_id'], ['devicePorts.id'], ),
    sa.ForeignKeyConstraint(['ipPool_id'], ['ipPools.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ipManage')
    ### end Alembic commands ###
