"""empty message

Revision ID: d27b3723b89d
Revises: None
Create Date: 2016-07-21 21:07:16.046773

"""

# revision identifiers, used by Alembic.
revision = 'd27b3723b89d'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('devicePowermanage')
    op.add_column('virtMachine', sa.Column('isdelete', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('virtMachine', 'isdelete')
    op.create_table('devicePowermanage',
    sa.Column('id', mysql.INTEGER(display_width=11), nullable=False),
    sa.Column('isdelete', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('remarks', mysql.TEXT(), nullable=True),
    sa.Column('instaff', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('inputtime', mysql.DATETIME(), nullable=True),
    sa.Column('enabled', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True),
    sa.Column('ip', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('password_hash', mysql.VARCHAR(length=64), nullable=True),
    sa.Column('powerid', mysql.VARCHAR(length=256), nullable=True),
    sa.Column('type', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True),
    sa.Column('user', mysql.VARCHAR(length=64), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
