"""empty message

Revision ID: ddd227fea0cd
Revises: 20688447519d
Create Date: 2016-06-05 23:17:04.795832

"""

# revision identifiers, used by Alembic.
revision = 'ddd227fea0cd'
down_revision = '20688447519d'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'powerstatus')
    op.add_column('devices', sa.Column('powerstatus', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('devices', 'powerstatus')
    op.add_column('assets', sa.Column('powerstatus', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    ### end Alembic commands ###
