"""empty message

Revision ID: e59dd178a641
Revises: 9aca554546b3
Create Date: 2016-05-28 17:09:58.283378

"""

# revision identifiers, used by Alembic.
revision = 'e59dd178a641'
down_revision = '9aca554546b3'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('asset_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['asset_id'], ['assets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'assets', sa.Column('assetclass_id', sa.Integer(), nullable=True))
    op.drop_constraint(u'assets_ibfk_1', 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'assettype', ['assetclass_id'], ['id'])
    op.drop_column(u'assets', 'assetclass')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'assets', sa.Column('assetclass', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key(u'assets_ibfk_1', 'assets', 'assettype', ['assetclass'], ['id'])
    op.drop_column(u'assets', 'assetclass_id')
    op.drop_table('device')
    ### end Alembic commands ###
