"""empty message

Revision ID: e9a0e817ae80
Revises: 9fa02b359b34
Create Date: 2016-05-28 16:20:40.609195

"""

# revision identifiers, used by Alembic.
revision = 'e9a0e817ae80'
down_revision = '9fa02b359b34'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('an', sa.String(length=64), nullable=True))
    op.add_column('assets', sa.Column('assetclass', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('brand', sa.String(length=64), nullable=True))
    op.add_column('assets', sa.Column('dateofmanufacture', sa.DateTime(), nullable=True))
    op.add_column('assets', sa.Column('equipprice', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('flowstatus', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('inputtime', sa.DateTime(), nullable=True))
    op.add_column('assets', sa.Column('inputuser', sa.String(length=64), nullable=True))
    op.add_column('assets', sa.Column('managedept', sa.String(length=64), nullable=True))
    op.add_column('assets', sa.Column('managestaff', sa.String(length=64), nullable=True))
    op.add_column('assets', sa.Column('manufacturer', sa.String(length=64), nullable=True))
    op.add_column('assets', sa.Column('model', sa.String(length=64), nullable=True))
    op.add_column('assets', sa.Column('onstatus', sa.Integer(), nullable=True))
    op.add_column('assets', sa.Column('remarks', sa.Text(), nullable=True))
    op.add_column('assets', sa.Column('sinceendtime', sa.DateTime(), nullable=True))
    op.add_column('assets', sa.Column('sincestarttime', sa.DateTime(), nullable=True))
    op.add_column('assets', sa.Column('site', sa.String(length=64), nullable=True))
    op.add_column('assets', sa.Column('sn', sa.String(length=64), nullable=True))
    op.add_column('assets', sa.Column('useasset', sa.String(length=128), nullable=True))
    op.add_column('assets', sa.Column('usedept', sa.String(length=64), nullable=True))
    op.add_column('assets', sa.Column('useendtime', sa.DateTime(), nullable=True))
    op.add_column('assets', sa.Column('usestaff', sa.String(length=64), nullable=True))
    op.add_column('assets', sa.Column('usestarttime', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_assets_an'), 'assets', ['an'], unique=True)
    op.drop_constraint(u'assets_ibfk_1', 'assets', type_='foreignkey')
    op.create_foreign_key(None, 'assets', 'assettype', ['assetclass'], ['id'])
    op.drop_column('assets', 'assettype')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('assets', sa.Column('assettype', mysql.INTEGER(display_width=11), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'assets', type_='foreignkey')
    op.create_foreign_key(u'assets_ibfk_1', 'assets', 'assettype', ['assettype'], ['id'])
    op.drop_index(op.f('ix_assets_an'), table_name='assets')
    op.drop_column('assets', 'usestarttime')
    op.drop_column('assets', 'usestaff')
    op.drop_column('assets', 'useendtime')
    op.drop_column('assets', 'usedept')
    op.drop_column('assets', 'useasset')
    op.drop_column('assets', 'sn')
    op.drop_column('assets', 'site')
    op.drop_column('assets', 'sincestarttime')
    op.drop_column('assets', 'sinceendtime')
    op.drop_column('assets', 'remarks')
    op.drop_column('assets', 'onstatus')
    op.drop_column('assets', 'model')
    op.drop_column('assets', 'manufacturer')
    op.drop_column('assets', 'managestaff')
    op.drop_column('assets', 'managedept')
    op.drop_column('assets', 'inputuser')
    op.drop_column('assets', 'inputtime')
    op.drop_column('assets', 'flowstatus')
    op.drop_column('assets', 'equipprice')
    op.drop_column('assets', 'dateofmanufacture')
    op.drop_column('assets', 'brand')
    op.drop_column('assets', 'assetclass')
    op.drop_column('assets', 'an')
    ### end Alembic commands ###
