"""empty message

Revision ID: eda9df135427
Revises: None
Create Date: 2016-07-11 00:11:22.591035

"""

# revision identifiers, used by Alembic.
revision = 'eda9df135427'
down_revision = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('assets', 'useendtime')
    op.drop_column('assets', 'usestarttime')
    op.add_column('virtmachine', sa.Column('deviceType', sa.String(length=64), nullable=True))
    op.drop_column('virtmachine', 'useendtime')
    op.drop_column('virtmachine', 'use')
    op.drop_column('virtmachine', 'usestarttime')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('virtmachine', sa.Column('usestarttime', mysql.DATETIME(), nullable=True))
    op.add_column('virtmachine', sa.Column('use', mysql.VARCHAR(length=64), nullable=True))
    op.add_column('virtmachine', sa.Column('useendtime', mysql.DATETIME(), nullable=True))
    op.drop_column('virtmachine', 'deviceType')
    op.add_column('assets', sa.Column('usestarttime', mysql.DATETIME(), nullable=True))
    op.add_column('assets', sa.Column('useendtime', mysql.DATETIME(), nullable=True))
    ### end Alembic commands ###
