"""empty message

Revision ID: f0fa8c0e67be
Revises: 7eb921f47794
Create Date: 2016-05-28 18:25:46.719944

"""

# revision identifiers, used by Alembic.
revision = 'f0fa8c0e67be'
down_revision = '7eb921f47794'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('IDC',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ispid', sa.String(length=64), nullable=True),
    sa.Column('contactid', sa.String(length=64), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('nettype', sa.String(length=64), nullable=True),
    sa.Column('address', sa.String(length=128), nullable=True),
    sa.Column('city', sa.String(length=64), nullable=True),
    sa.Column('adnature', sa.String(length=64), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('rack',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('staff', sa.String(length=64), nullable=True),
    sa.Column('seatno', sa.String(length=64), nullable=True),
    sa.Column('furnituretype', sa.String(length=64), nullable=True),
    sa.Column('size', sa.String(length=64), nullable=True),
    sa.Column('remainsize', sa.String(length=64), nullable=True),
    sa.Column('electrictype', sa.String(length=32), nullable=True),
    sa.Column('electricno', sa.String(length=32), nullable=True),
    sa.Column('electriccapacity', sa.String(length=32), nullable=True),
    sa.Column('leftelectric', sa.String(length=64), nullable=True),
    sa.Column('seattime', sa.DateTime(), nullable=True),
    sa.Column('expiretime', sa.DateTime(), nullable=True),
    sa.Column('nextpaytime', sa.DateTime(), nullable=True),
    sa.Column('money', sa.String(length=64), nullable=True),
    sa.Column('isdelete', sa.Boolean(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('instaff', sa.String(length=64), nullable=True),
    sa.Column('inputtime', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('rack')
    op.drop_table('IDC')
    ### end Alembic commands ###
