"""empty message

Revision ID: f18a59c627a0
Revises: 1674a58d7d0c
Create Date: 2016-07-30 15:50:47.663578

"""

# revision identifiers, used by Alembic.
revision = 'f18a59c627a0'
down_revision = '1674a58d7d0c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('deviceModel', sa.Column('portcount', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('deviceModel', 'portcount')
    ### end Alembic commands ###
